key: alkatraz:boulder_rune
allowed_item_types:
  - sword
  - axe
  - wand
triggers:
  - on_damage_dealt
  - on_kill
item:
  material: STONE
  display_name: '&7Boulder Rune'
  lore:
    - '&7&oA dense rune pulsing with earthen might.'
    - '&7&oCreates a small explosion on impact.'
attributes:
  alkatraz:earth_affinity: 10
effects:
  - type: explosion
    power: 2
    set_fire: false
    break_blocks: false
recipe:
  shape:
    - "   "
    - "SMS"
    - " M "
  ingredients:
    M: AMETHYST_SHARD
    S: STONE
