key: ender_rune
allowed_item_types:
  - leggings
  - boots
triggers:
  - on_sneak
item:
  material: ENDER_PEARL
  display_name: '&5Ender Rune'
  lore:
    - '&7&oA warped rune that bends space itself.'
    - '&7&oSneak to teleport the user a short distance.'
conditions:
  - type: cooldown
    seconds: 12
  - type: circle_level
    min_circle: 2
effects:
  - type: teleport
    distance: 8
recipe:
  shape:
    - " E "
    - " M "
    - " C "
  ingredients:
    M: alkatraz:magic_stone
    E: ENDER_PEARL
    C: CHORUS_FRUIT
