key: marksman_rune
allowed_item_types:
  - bow
  - crossbow
triggers:
  - on_projectile_hit
item:
  material: ARROW
  display_name: '&aMarksman Rune'
  lore:
    - '&7&oA precision rune that guides projectiles true.'
    - '&7&oIncreases projectile damage.'
conditions:
  - type: random
    chance: 0.35
  - type: circle_level
    min_circle: 1
effects:
  - type: damage
    damage: 4
recipe:
  shape:
    - " A "
    - "FMF"
    - "   "
  ingredients:
    M: alkatraz:magic_stone
    A: ARROW
    F: FLINT
