name: Alkatraz
version: '${project.version}'
main: me.nagasonic.alkatraz.Alkatraz
api-version: '1.19'
depend: [NBTAPI]
commands:
  spells:
    description: Opens Spells Gui
    usage: /spells
  alkatraz:
    description: Alkatraz Command
    usage: /alkatraz
