name: Alkatraz
version: '${project.version}'
main: me.nagasonic.alkatraz.Alkatraz
softdepend:
  - PlaceholderAPI
api-version: '1.19'
commands:
  spells:
    description: Opens Spells Gui
    usage: /spells
  alkatraz:
    description: Alkatraz Command
    usage: /alkatraz
  recipes:
    description: Opens the Recipe Book
    usage: /recipes
  cast:
    description: Cast a spell from the grimoire
    usage: /cast <token>
permissions:
  alkatraz.recipebook:
    description: Access to the Recipe Book
    default: true
