name: Test Plugin
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'          # match whatever your pom.xml targets
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Alkatraz
          path: target/Alkatraz.jar
 
  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        runtime: ['paper', 'spigot', 'purpur']
        version: ['1.21.11', '1.20.6', '1.19.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Alkatraz
          path: target
      - uses: NagasonicDev/TestMC@v1.0.0
        with:
          path: 'target/Alkatraz.jar'
          runtime: ${{ matrix.runtime }}
          version: ${{ matrix.version }}
          time: 120
          commands: |
            version
